# Generated by Django 3.2 on 2022-11-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20221120_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(verbose_name='زمان انتشار'),
        ),
    ]
