# Generated by Django 3.2 on 2022-11-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='توضیحات')),
                ('cerated', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
            ],
        ),
    ]
